import Head from 'next/head'

import BestSellers from './components/BestSellers'

import styles from '../../styles/Home.module.scss'
import Products from './components/Products'

export default function Home() {
  return (
    <>
      <Head>
        <title>XCO+ Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <BestSellers />
        <Products />
      </main>
    </>
  )
}
