import Head from 'next/head';
import axios from 'axios';
import React, { useState, useEffect } from 'react';

import BestSellers from './components/BestSellers';
import AllProducts from './components/Products';
import Loading from './components/Loader';

import styles from '../../styles/Home.module.scss';

export default function Home() {
  const [products, setProducts] = useState([]);
  const [bestSellers, setBestSellers] = useState([]);
  const [loading, setLoading] = useState(false);

  console.log("oi")

  useEffect(() => {
    setLoading(true);
    axios.get("/api/products")
      .then(({ data }) => {
        const allProducts = data.products;

        if (products.length !== allProducts.length) {
          setProducts(allProducts);
          setBestSellers(allProducts.filter(p => p.sales > 200));
        }
      })
      .catch(err => console.log(err))
      .finally(() => setLoading(false));
  }, [products.length]);

  return (
    <>
      <Head>
        <title>XCO+ Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        loading ? <Loading />
          :
          <main className={styles.main}>
            <BestSellers products={bestSellers} />
            <AllProducts products={products} />
          </main>
      }
    </>
  )
}
